USE DATABASE BANKING;

CREATE STAGE IF NOT EXISTS BANKING.RAW.S3_BANKING_STAGE
URL = 's3://banking--project/'
CREDENTIALS = (
AWS_KEY_ID = '<AWS_ACCESS_KEY_ID>'
AWS_SECRET_KEY = '<AWS_SECRET_ACCESS_KEY>')
FILE_FORMAT = (TYPE = PARQUET);
