name: CD


on:
  workflow_run:
    workflows: [CI]
    types:
      - completed

jobs:
  build-and-push:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Log in to GHCR
        uses: docker/login-action@v4
        with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Airflow image
        uses: docker/build-push-action@v7
        with:
          context: .
          file: ./airflow/Dockerfile
          push: true
          tags: |
            ghcr.io/akash-dev5/banking-airflow:latest
            ghcr.io/akash-dev5/banking-airflow:${{ github.sha }}
                